
server:
  port: 8081

spring:
  profiles:
    active: dev
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

bizppurio:
  token: 'https://api.bizppurio.com/v1/token'
  message: 'https://api.bizppurio.com/v3/message'
  url:
    apply_agree: 'https://forms.gle/QASXrzktUCiSxUkc6'
    photo_submit: 'https://forms.gle/5AkKyQoj3MYqu5mA8'
    photo_hurry: 'https://forms.gle/ihfhPSy3Fn8fdjmK7'
    refuse_change_form: 'https://yedu-tutor.com/teachersetting/login'
    result_share_form: 'https://yedu-tutor.com/result/'
    class_guide: 'https://2ly.link/2639z'

message:
  enable: true
