server:
  servlet:
    session:
      cookie:
        same-site: none
spring:
  graphql:
    graphiql:
      enabled: true
  config:
    import: optional:application-local.yml
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
jwt:
  refreshExpiration: 1209600
  accessExpiration: 86400


cloud:
  aws:
    credentials:
      instance-profile: false
    region:
      auto: false
    stack:
      auto: false

app:
  payment-api:
    web-client-properties:
      connection-time-out: 3
      read-time-out: 3
      write-time-out: 4
  discord-api:
    retry-count: 2
    retry-interval-seconds: 3
    web-client-properties:
      connection-time-out: 10
      read-time-out: 10
      write-time-out: 10


management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,mappings'


google:
  sheet:
    id: 1ArUez8CaKaRQU0vmeE-uvrOnY43u2VSBNV9V122222k
