name: Java CD with Gradle

on:
  push:
    branches:
      - "develop"
    paths:
      - .github/workflows/CD-api-develop.yml
      - "api/**"
      - "shared/**"
      - "build.gradle.kts"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env :
      working-directory: ./

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Create application.yml
      run: |
        echo "${{ secrets.API_APPLICATION_DEV }}" > ./api/src/main/resources/application-dev.yml
        echo "${{ secrets.API_APPLICATION_PROD }}" > ./api/src/main/resources/application-prod.yml
    

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew :api:jib
      working-directory: ${{ env.working-directory }}
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.EC2_SERVER_HOST }}
          username: ${{ secrets.EC2_SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker login ghcr.io -u "y-edu" -p '${{secrets.DEPLOY_TOKEN}}'
            docker pull ghcr.io/y-edu/api:1.0.0
            docker rm -f yedu_develop
            docker run -d \
            --name yedu_develop \
            -e "SPRING_PROFILES_ACTIVE=dev" \
            -e "TZ=Asia/Seoul" \
            -p 9191:8080 \
            -v "/logs-yedu:/app/logs" \
            -v "/was-logs-yedu:/app/was-logs" \
            --restart always \
            --network yedu-network \
            ghcr.io/y-edu/api:1.0.0
