name: Java CD with Gradle

on:
  push:
    paths:
      - .github/workflows/CD-consumer-develop.yml
      - .github/workflows/CI-consumer-develop.yml
      - "consumer/**"
      - "shared/**"
      - "build.gradle.kts"
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env :
      working-directory: ./

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Create application.yml
      run: |
        echo "${{ secrets.CONSUMER_APPLICATION_DEV }}" > ./consumer/src/main/resources/application-dev.yml
        echo "${{ secrets.CONSUMER_APPLICATION_PROD }}" > ./consumer/src/main/resources/application-prod.yml
        

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew :consumer:jib
      working-directory: ${{ env.working-directory }}
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.INFRABIRD_SERVER_HOST }}
          username: ${{ secrets.INFRABIRD_SERVER_USERNAME }}
          key: ${{ secrets.INFRABIRD_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u "y-edu" -p '${{secrets.DEPLOY_TOKEN}}'
            docker pull ghcr.io/y-edu/consumer:1.0.0
            docker rm -f yedu_develop_consumer
            docker run -d \
            --name yedu_develop_consumer \
            -e "SPRING_PROFILES_ACTIVE=dev" \
            -e "TZ=Asia/Seoul" \
            --restart always \
            ghcr.io/y-edu/consumer:1.0.0
